version: '2.3'
services:
  server:
    build: .
    container_name: rbtm-experiment
    volumes:
      - ./logs:/var/www/experiment/logs
    external_links:
      - tango-ds
    ports:
      - "5001:5001"
    networks:
      - default
      - rbtm-drivers_default
    restart: unless-stopped

networks:
  rbtm-drivers_default:
    external: true
